### ISSUE TITLE
FormatVersion check failed

### ISSUE THREAD

**Issue by fengbujue2022** [turgayozgur/Owin.Token.AspNetCore#1]
https://github.com/turgayozgur/Owin.Token.AspNetCore/blob/57034c3eb21a6af0156cdd049003c80d36baeca0/src/Owin.Token.AspNetCore/TicketSerializer.cs#L48-L51

hi Turgay, thanks for you great work first !

If skip "return null", I could correctly deserialize the ticket
What does this checking for?  Will it have any impact if skipped ?

**Comment by turgayozgur** [comment]
Hi @Feng-Bu-Jue, the ticket serializer inspired by the original .NET Framework code. Most of the parts copied from. So, I don't know what is for.

On line 56, the `reader.ReadInt32()` method was called again to get a `count`. Looks like there is no requirement to check the value is equal to `FormatVersion`.

If you open a new pull request that removes that check, I can merge it.

**Comment by fengbujue2022** [comment]
https://github.com/aspnet/AspNetKatana/blob/7aa465d56878b43409a603cf5384e7614cc35e19/src/Microsoft.Owin.Security/DataHandler/Serializer/TicketSerializer.cs#L93

I figured it out, It is caused by Issue token code‘s FormatVersion = 2 (OWIN version is 3.0 ), this checking should working fine with newer OWIN
